### PR TITLE
swapping kv from infra-vault-sbox to infra-vault-nonprod

### PR DESCRIPTION
**Pull request by thomast1906**
### Change description ###
swapping kv from infra-vault-sbox to infra-vault-nonprod

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Review by timja — COMMENTED** [review]
Why?

**Comment by thomast1906** [comment]
@timja majority of our repos use hmcts-nonprod already; was swapping the others that use hmcts-sbox to this as we are just copying the secret between the two.

serviceConnection is the same, example here: https://github.com/hmcts/aks-sds-deploy/blob/master/azure-pipelines.yml#L88-L90

**Comment by timja** [comment]
> @timja majority of our repos use hmcts-nonprod already; was swapping the others that use hmcts-sbox to this as we are just copying the secret between the two.
> 
> serviceConnection is the same, example here: [hmcts/aks-sds-deploy@`master`/azure-pipelines.yml#L88-L90](https://github.com/hmcts/aks-sds-deploy/blob/master/azure-pipelines.yml?rgh-link-date=2022-11-30T15%3A33%3A52Z#L88-L90)

sure i think quite a lot use sandbox too

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
hmm the sandbox sc shouldn't really be accessing non prod vault

**Comment by thomast1906** [comment]
secret was rotated into sbox KV - closing for now

**Pull request closed without merging**
